version: '3.9'

services:
  app:
    build: .
    container_name: backend_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/

